{% set name = "ocaml-camlp5" %}
{% set version = "710" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/camlp5/camlp5/archive/rel{{ version.replace(".", "") }}.tar.gz
  sha256: 83dff83d33ee9b70cd1b9d8d365db63a118201e5feb6aab49d9d3b1d62621784
  patches:
    - fix_where.diff

build:
  number: 0
  skip: True  # [win]

requirements:
  host:
    - ocaml
    - ocaml-findlib
  run:
    - ocaml

test:
  commands:
    - camlp5 -help
    - if [[ ! "$(camlp5 -where)" == "$PREFIX/lib/ocaml/camlp5" ]]; then exit 1; fi

about:
  home: https://camlp5.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Preprocessor / Pretty Printer for OCaml'
  doc_url: https://camlp5.github.io/doc/htmlc/
  dev_url: https://github.com/camlp5/camlp5

extra:
  recipe-maintainers:
    - isuruf
    - slel
