{% set name = "ocaml-camlp5" %}
{% set version = "712" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/camlp5/camlp5/archive/rel{{ version.replace(".", "") }}.tar.gz
  sha256: fc4b50b9d917c2f844b909bdfd55735f3f658e32a415f0decc1c265bf3af42be
  patches:
    - fix_where.diff

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - ocaml
    - ocaml-findlib
  run:
    - ocaml

test:
  commands:
    - camlp5 -help
    - if [[ ! "$(camlp5 -where)" == "$PREFIX/lib/ocaml/camlp5" ]]; then exit 1; fi

about:
  home: https://camlp5.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Preprocessor / Pretty Printer for OCaml
  doc_url: https://camlp5.github.io/doc/htmlc/
  dev_url: https://github.com/camlp5/camlp5

extra:
  recipe-maintainers:
    - isuruf
    - slel
