travis:
  secure:
    BINSTAR_TOKEN: X+iwfM22uI8EQs6xGOpFLvI6UbiWyZpgl86KlyvOsonKypWNbQskb7hfYF6OkMAk1/PS8Y05cDGVQYIXcOTFu4CoF+pibk2kr4lTeCwhfUOLZPR6ok25fNTW053PCUOfXZGTrLLsAzSJzeAA9emgQWlDLYqJ6Wn3UOU6OFlxgPpmVrgo7phQtyzv/GL0i3UH9+kSLKBQzpmRBXtSCgJSIyQOuWe2kXWSDueHd1w7sdG9vo27f8WskyPfaz2KfhFr2UPpdPjjKZ+Kx9Db52WJ3IzQi6sh0og8gPVbU+VWq/dp0BtLG3uzZie1L51E0dVVGzYrpd18Cn8CRERIeW6vXGYno7APhUaI6NPt/pTAlIwzJq6/HGP+q9PEMLvPLTUsXj+dp7s4MFWo26y2Ex9z/W8tbXEcJH1SLPrFz4nlAu8Mkw46j2FKjAhy125IJkGdA1YIC2Kw45JCWpb62mwmBwh4quDBhPJ1ehMMczG8AJ0WddVRwzPxc15RzjbaL8hieFkWChfFu446ByL0bEJRpRRukU/v/mGyK/FwETq1Ox5WGsJNdpGr5HLxZXDTbVWrVD1IKwU7bBusY6peeLrd2nKN+0CwpYqK9vSii9uVcwEOKdbINITZ9LCK1ztzwlzcaGGgqCbqHouaZxn+UqpJGDypJVE1+k5ZlLhgvQ9kl2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
